### ISSUE TITLE
Roadmap 3.0

### ISSUE THREAD

**Issue by kdubuc** [SDIS62/prevarisc#610]
- [ ] Suppression de la gestion des rues, communes, adresses. Mise en place d'un geocoder qui sera responsable de la géolocalisation et de l'obtention d'un point adresse pour un établissement. https://github.com/SDIS62/prevarisc/issues/361
- [ ] Suppression de la gestion des textes applicables et des prescriptions. Proposition des textes grâce à Legifrance via une API, et sauvegarde en local des modifications apportées (qui seraient proposées lors d'ajouts du même texte sur les autres dossiers / établissements).
- [ ] Suppression du module API. Trop léger et trop inutile pour le moment, il sera remodelé, et formera la base de la 4.x.
- [ ] Gestion des commissions / calendriers revue (calendrier exportable, membres etc ..) https://github.com/SDIS62/prevarisc/issues/477 https://github.com/SDIS62/prevarisc/issues/548 https://github.com/SDIS62/prevarisc/issues/561
- [ ] Gestion des documents revue avec la mise en place d'un vrai système de stockage https://github.com/SDIS62/prevarisc/issues/318 https://github.com/SDIS62/prevarisc/issues/325
- [ ] Gestion des groupement deviendra une gestion de zone https://github.com/SDIS62/prevarisc/issues/606
- [ ] Ajout d'un workflow pour les interactions entre établissement et dossier https://github.com/SDIS62/prevarisc/issues/275 https://github.com/SDIS62/prevarisc/issues/605
- [ ] Améliorations dans le module des documents consultés : 
  - Permettre modification du libellé des documents consultés
  -  Pièce jointe dans documents consultés
  - Proposition des documents consultés https://github.com/SDIS62/prevarisc/issues/326
- [ ] Dans recherche, affichage du numéro et de la rue,  ajout des critères groupement / par agent prev
- [ ] Filtrer l’affichage des établissements via la matrice des droits
- [ ] Ajout / modification des 3 niveaux de validation du dossier (non verrouillé = En attente, verrouillé = Validé, Avis de commission mis = Traité) https://github.com/SDIS62/prevarisc/issues/501
- [ ] repartition de la charge dans ODJ (barre de progression dans les 3 niveaux)
- [ ] Récupération de la commission du parent d'une cellule / habitation quand on accède à un dossier pour les droits +  La commission de compétence de l’utilisateur doit être la commission qui s’inscrit quand je crée un dossier (ex : commission de Lens ne peut créer que des dossiers dont la compétence est la commission de Lens)
- [ ] affichage fermé / projet à différencier 
- [ ] Descriptif site
- [ ] Nouvelle approche du compte utilisateur https://github.com/SDIS62/prevarisc/issues/479
- [ ] Version allégé et plus stable de la génération de documents https://github.com/SDIS62/prevarisc/issues/534 https://github.com/SDIS62/prevarisc/issues/598
- [ ] Recherche par zone https://github.com/SDIS62/prevarisc/issues/570
- [ ] Mise en place de dépendances limitant le lien fort avec zf1 via un container https://github.com/container-interop/container-interop
  - Cache psr6
  - Flysystem pour la gestion des fichiers
  - Twig (?) pour les vues
  - Doctrine pour la persistance 
  - Zend ACL, Zend LDAP
- [ ] Redesign des vues
  - Bootstrap 3
  - gestion des dépendances via bower ?
- [ ] Changer l'algo de chiffrement du mot de passe
- [ ] Système de notifications en temps réél
- [ ] PHP 7.1
- [ ] Suppression des ERP / DOSS

Une des pistes actuellement évoquées en interne est de développer un module DECI : gestion des poteaux d'eau pour suivre le décret du 27 Février 2015 qui modifie la partie réglementaire du Code de la Construction et de l’Habitation https://github.com/SDIS62/prevarisc/issues/597

**Comment by A511701** [comment]
Voici le top 10 des demandes d'évolutions remontées par nos clients :
- [ ] Suppression des établissements et des dossiers
- [ ] Lorsqu'on créé une date dans le calendrier dans la page d'édition / création d'un dossier, que cette date soit automatiquement sélectionnée et qu'on ait pas à recliquer dessus
- [ ] Ajouter un bouton "sauvegarder" en bas de la page de création / édition d'un dossier
- [ ] Pouvoir rechercher un établissement par son numéro dans la voie OU afficher l'adresse complète dans les résultats de recherche
- [ ] Améliorer globalement la génération de documents types : pouvoir mettre du markdown à partir d'un wisiwig, que les boucles ne soient pas obligatoires, pouvoir mettre des structures conditionnelles (si pas de prescriptions, alors ...)
- [ ] Améliorer le descriptif technique d'un établissement
- [ ] Avoir une signature électronique sur les pièces jointes
- [ ] Ajouter automatiquement les textes applicables aux dossiers /ets en fonction de leur type / catégorie / genre
- [ ] Avoir un outil pour l'aide au suivi d'activité du chef de groupement, notamment l'aide à la planification des visites périodiques à l'année N+1
- [ ] Pouvoir ajouter facilement des natures de dossier
- [ ] Avoir une date de réponse au service "réelle" à l'issue de la commission pour un dossier pour faire des statistiques sur les dossiers traités telle ou telle année
